var a, b, c, d, e, f, x, y, z;
a = 1 + 2 * 3 / 5;
b = (1 + 2) * 3 / 5;
c = (1 + 2) * (3 - 5);
d = x | y ^ z;
e = (x | y) ^ z;
a = true || false && null;
b = c == d || e != f;
c = x instanceof y || x instanceof z;
d = x == y && y != z;
a = 1.1.toString();
b = new A().toString();
c = new x.A().toString();
d = new x.y().z();
var r = /ab+c/i.exec('abc');
